[project]
name = "fairnessnsp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pulp>=3.2.2",
    "pandas>=2.0.3",
    "streamlit>=1.28.0",
]
